name: Run Tests and Build Web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run all tests
        run: ./gradlew allTest
        env:
          GITHUB_ACTOR: simon-duchastel
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            composeApp/build/reports/tests/
            build/reports/tests/

  build_and_deploy_wasm:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build browser distribution
        run: ./gradlew wasmJsBrowserDistribution
        env:
          GITHUB_ACTOR: simon-duchastel
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

      - name: Copy productionExecutable to webOutput
        run: |
          ls composeApp
          ls composeApp/build
          ls composeApp/build/dist
          ls composeApp/build/dist/wasmJs
          ls composeApp/build/dist/wasmJs/productionExecutable/
          ls webOutput
          mkdir -p webOutput
          cp -r composeApp/build/dist/wasmJs/productionExecutable/* webOutput/

      - name: Deploy to releases branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin
          git checkout -B releases
          rm -rf ./*
          cp -r webOutput/* .
          git add .
          git commit -m "Deploy WebAssembly build from main"
          git push origin releases --force
        env:
          GITHUB_ACTOR: simon-duchastel
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
